### PR TITLE
Merging experimental into master

### PR DESCRIPTION
**Pull request by drexample**
Tests passed, no crashes

### CODE REVIEW

**Comment by CDRDecky** [comment]
travis don't do this

**Comment by Michiyamenotehifunana** [comment]
Travis is just fucking up on indentations, it's fine as long as it actually compiles.

**Comment by CDRDecky** [comment]
advanced

also advanced s h i t p o s t i n g   on dev

**Comment by CDRDecky** [comment]
@Little Lost Nestor#0358

**Pull request merged**
